baseURL: https://blog.dacio.dev/
languageCode: en-us
title: Dacio's Tech Blog
theme: hyde
disqusShortname: dacio

pygmentsCodeFences: true
pygmentsOptions: linenos=inline

permalinks:
  posts: /:year/:month/:day/:slug/

params:
  description: The blog of an SF-based learner/programmer.

Menus:
  main:
    - Name: GitHub
      URL: https://github.com/dacioromero/
    - Name: LinkedIn
      URL: https://www.linkedin.com/in/dacioromero/
