baseURL: https://blog.dacio.dev/
languageCode: en-us
title: Dacio's Tech Blog
theme: hugo-coder
disqusShortname: dacio

permalinks:
  posts: /posts/:year/:month/:day/:slug/

params:
  author: Dacio Romero
  description: The blog of an SF-based learner/programmer.
  info: Full-stack Software Engineer
  gravatar: dacioromero@gmail.com
  keywords: blog,developer
  hideCredits: true
  since: 2019
  colorScheme: auto
  social:
    - name: GitHub
      icon: fab fa-github fa-2x
      url: https://github.com/dacioromero/
    - name: LinkedIn
      icon: fab fa-linkedin-in fa-2x
      url: https://www.linkedin.com/in/dacioromero/
    - name: Twitter
      icon: fab fa-twitter fa-2x
      url: https://twitter.com/dacioromero

menu:
  main:
    - name: Blog
      url: /posts/
